Key vault secret status
equinor/radix-api pull request #409
Opened 2022-07-18 14:05 UTC by satr

2022-07-19 12:02 UTC, nilsgstrabo requested changes
A few minor suggestions as we discussed

2022-07-20 07:48 UTC, satr commented on api/secrets/models/azure-key-vault-secret-status.go
> +type AzureKeyVaultSecretVersion struct {
Fixed

2022-07-20 08:02 UTC, satr commented on api/secrets/models/secret_status.go
> +	Orphan
Fixed

2022-07-20 08:02 UTC, satr commented on api/secrets/models/secret.go
>  	SecretTypeOrphaned              SecretType = "orphaned"
Removed

2022-07-20 08:03 UTC, satr commented on api/secrets/secret_handler.go
> +		//activeCsiSecretProviderClassNameSet := deploymentsCsiSecretProviderNameSetMap[component.GetName()]
Removed

2022-07-20 08:03 UTC, satr commented on api/secrets/secret_handler.go
> +		//activeCsiSecretProviderClassNameSet := deploymentsCsiSecretProviderNameSetMap[jobComponent.GetName()]
Removed

2022-07-20 08:03 UTC, satr commented on api/secrets/secret_handler.go
> +			secretStatus := getAzureKeyVaultSecretStatus(azureKeyVault.Name, secretProviderClassMap, csiSecretStoreSecretMap)
Moved

2022-07-20 08:13 UTC, nilsgstrabo approved these changes

2022-07-20 10:16 UTC, merged