Use Replica Override to manually scale a component
equinor/radix-api pull request #665
Opened 2024-08-27 08:50 UTC by Richard87

2024-09-03 10:50 UTC, satr commented on api/deployments/models/component_deployment.go
> +	// Set if manuall control of replicas is in place. null means automatic controll, 0 means stopped and >= 1 is manually scaled.
```suggestion
	// Set if manual control of replicas is in place. Not set means automatic control, 0 means stopped and >= 1 is manually scaled.
```

2024-09-03 10:55 UTC, satr commented on api/environments/component_handler.go
> +	log.Ctx(ctx).Info().Msgf("Resetting manuall scaled component %s, %s", componentName, appName)
```suggestion
	log.Ctx(ctx).Info().Msgf("Resetting manually scaled component %s, %s", componentName, appName)
```

2024-09-03 11:23 UTC, satr requested changes

2024-09-03 11:23 UTC, satr commented on api/deployments/models/component_status.go
> +func isCopmonentRestarting(component radixv1.RadixCommonDeployComponent, rd *radixv1.RadixDeployment) bool {
```suggestion
func isComponentRestarting(component radixv1.RadixCommonDeployComponent, rd *radixv1.RadixDeployment) bool {
```

2024-09-03 11:23 UTC, satr commented on api/deployments/models/component_status.go
> +	if isCopmonentRestarting(component, rd) {
```suggestion
	if isComponentRestarting(component, rd) {
```

2024-09-03 11:23 UTC, satr commented on api/deployments/models/component_status.go
> +	if strings.EqualFold(restarted, "") {
```suggestion
	if restarted == "" {
```
No need for case insesitive comparison

2024-09-03 11:23 UTC, satr commented on api/deployments/models/component_status.go
> +	return false
```suggestion
	return reconciledTime.IsZero() || restartedTime.After(reconciledTime.Time)
```

2024-09-04 07:13 UTC, satr requested changes

2024-09-04 07:44 UTC, satr commented on api/environments/environment_handler.go
> +			}
```suggestion
		if override := deployComponent.GetReplicasOverride(); override != nil && *override == 0 {
			if err := eh.ResetScaledComponent(ctx, appName, envName, deployComponent.GetName(), true); err != nil {
				return err
			}
```

2024-09-04 07:46 UTC, satr commented on api/environments/environment_handler.go
>  	}
```suggestion
	}
	if rd == nil {
		return nil, http.ValidationError(v1.KindRadixDeployment, "no radix deployments found")
	}
```

2024-09-04 07:48 UTC, satr commented on api/kubequery/deployment.go
> +func GetDeploymentForComponent(ctx context.Context, client kubernetes.Interface, appName, envName, componentName string) (*appsv1.Deployment, error) {
Is it in use?

2024-09-04 07:48 UTC, satr commented on api/environments/component_handler.go
> +	radixDeployment, err := kubequery.GetLatestRadixDeployment(ctx, eh.accounts.UserAccount.RadixClient, appName, envName)
Add docs comment

2024-09-04 07:51 UTC, satr commented on api/utils/predicate/kubernetes.go
> +		radixlabels.ForComponentName(componentName)))
```suggestion
	selector := labelselector.ForComponent(appName, componentName).AsSelector()
```

2024-09-04 08:11 UTC, Richard87 commented on api/kubequery/deployment.go
> +func GetDeploymentForComponent(ctx context.Context, client kubernetes.Interface, appName, envName, componentName string) (*appsv1.Deployment, error) {
Thanks, removed :)

2024-09-04 08:37 UTC, satr submitted a review, later dismissed

2024-09-05 12:07 UTC, satr submitted a review, later dismissed

2024-09-06 07:07 UTC, satr approved these changes

2024-09-11 05:58 UTC, satr approved these changes

2024-09-11 05:59 UTC, merged